baseURL: "https://yavorkostadinov.netlify.app/"
languageCode: en-us
title: 'Yavor A Kostadinov'
theme: 'PaperModLocal'

relativeURLs: false
canonifyURLs: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Yavor A Kostadinov
  description: "This is the website of Dr. Yavor A Kostadinov."
  keywords: [international relations, diplomacy, security]
  author: Yavor A Kostadinov
  # author: ["Me", "You"] # multiple authors
  DateFormat: "January 2, 2025"
  defaultTheme: # light
  disableThemeToggle: true
  customCSS: ["css/custom.css"]

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Yavor"
    icon: /images/home.png
    iconHeight: 30

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Hello! &#128075; Welcome!" 
    subtitle: "Thank you for visiting! Yavor A Kostadinov (森亞博) is an Assistant Professor whose teaching and supervision extend across undergraduate and graduate study. His research, focused on international organizations, security, diplomacy, and public policy, has produced a monograph and numerous articles. He has presented his work widely, received several grants and awards, and contributed to governmental projects. In service to the discipline, he reviews for international journals and continues to guide the next generation of scholars."
    imageUrl: "/images/Yavor.jpg"
    imageWidth: 200
    imageHeight: 200
    imageTitle: IR Professor
    buttons:
      - name: Teaching
        url: teaching
      - name: Research
        url: research
      - name: Services
        url: services
  
  socialIcons:
    - name: ORCID
      url: "https://orcid.org/0000-0003-2942-9532"
    - name: ResearchGate
      url: "https://www.researchgate.net/profile/Yavor-Kostadinov-2"
    - name: LinkedIn
      url: "https://tw.linkedin.com/in/yavor-kostadinov-281a4735"
    - name: facebook
      url: "https://www.facebook.com/yavors.corner"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<Senyabo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: downloads
      name: Downloads
      url: /downloads/
      weight: 6
    - identifier: impact
      name: Impact
      url: /impact/
      weight: 3
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 7
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
    - identifier: gallery
      name: Gallery
      url: /gallery/
      weight: 5
    - identifier: awards
      name: Awards
      url: /awards/
      weight: 4
    

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
  goldmark:
    renderer:
      unsafe: true
---